[phases.setup]
nixPkgs = ["python312", "python312Packages.pip"]

[phases.install]
cmds = [
  "python3 -m pip install -r bot/requirements.txt",
  "python3 -m pip install -r bot_raphael/requirements.txt"
]

[start]
cmd = "bash start.sh"
