import { NextRequest, NextResponse } from "next/server"
import db from "@/lib/db"
import { ensureFxSchemaAndBackfill, historicalUsdThb, isFxApplicable } from "@/lib/fx"
export const dynamic = "force-dynamic"
export async function GET(req: NextRequest) { try { await ensureFxSchemaAndBackfill(); const holdingId = new URL(req.url).searchParams.get("holdingId"); const result = holdingId ? await db.execute({ sql: "SELECT t.*, h.symbol, h.name FROM transactions t LEFT JOIN holdings h ON t.holding_id = h.id WHERE t.holding_id = ? ORDER BY t.date DESC", args: [holdingId] }) : await db.execute("SELECT t.*, h.symbol, h.name FROM transactions t LEFT JOIN holdings h ON t.holding_id = h.id ORDER BY t.date DESC"); return NextResponse.json(result.rows) } catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Internal server error" }, { status: 500 }) } }
export async function POST(req: NextRequest) { try {
  await ensureFxSchemaAndBackfill(); const { holdingId, type, quantity, price, fees, date, notes, fxFeeThb = 0, purchaseFxRate } = await req.json()
  if (!holdingId || !["BUY", "SELL"].includes(type) || !Number.isFinite(quantity) || quantity <= 0 || !Number.isFinite(price) || price < 0 || !/^\d{4}-\d{2}-\d{2}$/.test(date)) return NextResponse.json({ error: "Invalid transaction" }, { status: 400 })
  const holdingResult = await db.execute({ sql: "SELECT type FROM holdings WHERE id = ?", args: [holdingId] }); const holding = holdingResult.rows[0]; if (!holding) return NextResponse.json({ error: "Holding not found" }, { status: 404 })
  const suppliedFxRate = purchaseFxRate == null || purchaseFxRate === "" ? null : Number(purchaseFxRate); if (suppliedFxRate != null && (!Number.isFinite(suppliedFxRate) || suppliedFxRate <= 0)) return NextResponse.json({ error: "FX rate must be a positive THB-per-USD value" }, { status: 400 }); let rate: number | null = null, originalCost: number | null = null, status = "not_applicable"
  if (type === "BUY" && isFxApplicable(String(holding.type))) { rate = suppliedFxRate ?? await historicalUsdThb(date); status = rate == null ? "incomplete" : "complete"; originalCost = rate == null ? null : (quantity * price + Number(fees ?? 0)) * rate + Number(fxFeeThb || 0) }
  const id = crypto.randomUUID(); await db.batch([{ sql: "INSERT INTO transactions (id, holding_id, type, quantity, price, fees, date, notes, purchase_fx_rate, original_cost_thb, fx_fee_thb, fx_data_status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", args: [id, holdingId, type, quantity, price, fees ?? 0, date, notes ?? null, rate, originalCost, Number(fxFeeThb || 0), status] }, { sql: "UPDATE holdings SET updated_at = datetime('now') WHERE id = ?", args: [holdingId] }])
  const result = await db.execute({ sql: "SELECT * FROM transactions WHERE id = ?", args: [id] }); return NextResponse.json(result.rows[0], { status: 201 })
} catch (error) { return NextResponse.json({ error: error instanceof Error ? error.message : "Internal server error" }, { status: 500 }) } }