"use client"
import { useState } from "react"

type Transaction = { id: string; type: "BUY" | "SELL"; quantity: number; price: number; fees: number; date: string; notes: string | null; fx_fee_thb?: number | null }
export default function TransactionEditor({ transaction, onClose }: { transaction: Transaction; onClose: () => void }) {
  const [form, setForm] = useState({ type: transaction.type, quantity: String(transaction.quantity), price: String(transaction.price), fees: String(transaction.fees ?? 0), fxFeeThb: String(transaction.fx_fee_thb ?? 0), date: transaction.date, notes: transaction.notes ?? "" })
  const [saving, setSaving] = useState(false); const [error, setError] = useState("")
  const save = async () => { setSaving(true); setError(""); try { const response = await fetch(`/api/transactions/${transaction.id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, quantity: Number(form.quantity), price: Number(form.price), fees: Number(form.fees), fxFeeThb: Number(form.fxFeeThb) }) }); const body = await response.json(); if (!response.ok) throw new Error(body.error || "Unable to save"); window.location.reload() } catch (e) { setError(e instanceof Error ? e.message : "Unable to save") } finally { setSaving(false) } }
  return <div className="pf-tx-editor"><div className="pf-tx-editor-head"><strong>Edit transaction</strong><button onClick={onClose}>Cancel</button></div><div className="pf-tx-editor-fields"><label>Type<select value={form.type} onChange={e => setForm({ ...form, type: e.target.value as "BUY" | "SELL" })}><option>BUY</option><option>SELL</option></select></label><label>Quantity<input type="number" min="0" step="any" value={form.quantity} onChange={e => setForm({ ...form, quantity: e.target.value })}/></label><label>Price (USD)<input type="number" min="0" step="any" value={form.price} onChange={e => setForm({ ...form, price: e.target.value })}/></label><label>Fee (USD)<input type="number" min="0" step="any" value={form.fees} onChange={e => setForm({ ...form, fees: e.target.value })}/></label><label>FX fee (THB)<input type="number" min="0" step="any" value={form.fxFeeThb} onChange={e => setForm({ ...form, fxFeeThb: e.target.value })}/></label><label>Date<input type="date" value={form.date} onChange={e => setForm({ ...form, date: e.target.value })}/></label><label className="pf-tx-editor-notes">Notes<input value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })}/></label></div>{error && <p className="pf-error">{error}</p>}<button className="pf-btn-primary" disabled={saving} onClick={save}>{saving ? "Saving…" : "Save transaction"}</button></div>
}